export const videoData = [
  {
    id: '1',
    video: require('./assets/video/reel1.mp4'),
    profile: require('./assets/Rectangle1.png'),
    username: 'shasha_78',
    description: 'Attended the concert last ...',
    coins: '1.5K',
    views: 63,
    rockets: 63,
    heartbreaks: 8,
    comments: '50K',
  },
  {
    id: '2',
    video: require('./assets/video/reel3.mp4'),
    profile: require('./assets/Rectangle1.png'),
    username: 'shasha_78',
    description: 'Attended the concert last ...',
    coins: '1.5K',
    views: 63,
    rockets: 63,
    heartbreaks: 8,
    comments: '50K',
  },
  {
    id: '3',
    video: require('./assets/video/reel2.mp4'),
    profile: require('./assets/Rectangle1.png'),
    username: 'shasha_78',
    description: 'Attended the concert last ...',
    coins: '1.5K',
    views: 63,
    rockets: 63,
    heartbreaks: 8,
    comments: '50K',
  },
  {
    id: '4',
    video: require('./assets/video/first.mp4'),
    profile: require('./assets/Rectangle1.png'),
    username: 'shasha_78',
    description: 'Attended the concert last ...',
    coins: '1.5K',
    views: 63,
    rockets: 63,
    heartbreaks: 8,
    comments: '50K',
  },
  {
    id: '5',
    video: require('./assets/video/reel4.mp4'),
    profile: require('./assets/Rectangle1.png'),
    username: 'shasha_78',
    description: 'Attended the concert last ...',
    coins: '1.5K',
    views: 63,
    rockets: 63,
    heartbreaks: 8,
    comments: '50K',
  },
];
